### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by xee95** [Steem-FOSSbot/steem-fossbot-voter#127]
how i get BOT_API_KEY ?

**Comment by DavidFnck** [comment]
Have you check this? Or do you not really understand it?
![image](https://user-images.githubusercontent.com/9395343/35767001-3d0d2250-091e-11e8-8e7c-7eb88a8448fc.png)

1. The `BOT_API_KEY` is set by you when you deploy the bot to the heroku.
2. The way to generate it is up to you. @thrize recommend use `openssl`, but that's way requires you have installed it. 
3. If not, I think you can use any complicate password and it will work, ATTENTION PLS! Don't forget it.Otherwise you have to delete the Heroku deployment, and deploy it once again.

Hope to be helpful, good luck!

**Comment by thrize** [comment]
Thanks @DavidFnck , closing this

**Comment by xee95** [comment]
Thanks @DavidFnck
